// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC781HJMfrgCHl8tAc1KOZEYGLn2LLbMIs',
    appId: '1:653677327927:web:eaa4a9377225e3980db1b2',
    messagingSenderId: '653677327927',
    projectId: 'asur-snu',
    authDomain: 'asur-snu.firebaseapp.com',
    storageBucket: 'asur-snu.appspot.com',
    measurementId: 'G-84E4XWJPJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEdHNcsVHUHU5_ROTd1F_H_DErJXqsRc',
    appId: '1:653677327927:android:a556c54f834cb1f40db1b2',
    messagingSenderId: '653677327927',
    projectId: 'asur-snu',
    storageBucket: 'asur-snu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDsuFnxZEpboSWE1ueuvIVWONHVEzHb4',
    appId: '1:653677327927:ios:2b9faa6f85dec30c0db1b2',
    messagingSenderId: '653677327927',
    projectId: 'asur-snu',
    storageBucket: 'asur-snu.appspot.com',
    iosClientId:
        '653677327927-45fglu294vl1t06pkforp48qt1ht086h.apps.googleusercontent.com',
    iosBundleId: 'com.example.asur',
  );
}
